### ISSUE TITLE
Change export format parameter names

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice_file_import#6]
The `file_type` parameter should be renamed `output_format` to match teraslice_file_export.

The options should be:

`json_array` - Array wrapped JSON. Replaces `import`
`json_lines` - One JSON record per line. Replaces `file`

**Comment by jsnoble** [comment]
Shouldn't this instead be set to import_format or input_format? The output_format makes sense for the exporter, but this is a importer

**Comment by kstaken** [comment]
Yeah, although both should probably just be changed to `format`
